/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package demo;

import com.jaxio.jpa.querybyexample.GenericRepository;

import javax.inject.Named;
import javax.inject.Singleton;

@Named
@Singleton
public class AccountRepository extends GenericRepository<Account, Integer> {

    public AccountRepository() {
        super(Account.class);
    }

    @Override
    public Account getNew() {
        return new Account();
    }
}