/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package demo;

import com.jaxio.jpa.querybyexample.GenericRepository;
import org.springframework.transaction.annotation.Transactional;

import javax.inject.Named;
import javax.inject.Singleton;

/**
 * {@link GenericRepository} for {@link Account}
 */
@Named
@Singleton
public class AccountRepository extends GenericRepository<Account, String> {

    public AccountRepository() {
        super(Account.class);
    }

    @Override
    public Account getNew() {
        return new Account();
    }

    /**
     * Return the persistent instance of {@link Account} with the given unique property value username,
     * or null if there is no such persistent instance.
     *
     * @param username the unique value
     * @return the corresponding {@link Account} persistent instance or null
     */
    @Transactional(readOnly = true)
    public Account getByUsername(String username) {
        return findUniqueOrNone(new Account().username(username));
    }


}