DROP ALL OBJECTS;

CREATE TABLE ADDRESS (
    id                          int not null IDENTITY,
    street_name                 varchar(100),
    city                        varchar(100) not null,
    version                     int default 0,

    primary key (id)
);

CREATE TABLE ACCOUNT (
    id                       char(32) not null,
    login                    varchar(100) not null,
    password                 varchar(100) not null,
    email                    varchar(100) not null,
    is_enabled               bool,
    civility                 char(2),
    first_name               varchar(100),
    last_name                varchar(100),
    birth_date               timestamp,
    description              varchar(255),
    address_id               int,
    creation_date            timestamp,
    creation_author          varchar(200),
    last_modification_date   timestamp,
    last_modification_author varchar(200),
    version                  int default 0, 

    constraint account_unique_1 unique (login),
    constraint account_unique_2 unique (email),
    constraint account_fk_1 foreign key (address_id) references ADDRESS,
    primary key (id)
);

CREATE TABLE ROLE (
    id        int          generated by default as identity,
    role_name varchar(100) not null,

    constraint role_unique_1 unique (role_name),
    primary key (id)
);

CREATE TABLE ACCOUNT_ROLE (
    account_id  char(32) not null,
    role_id     int not null,

    constraint account_role_fk_1 foreign key (account_id) references ACCOUNT,
    constraint account_role_fk_2 foreign key (role_id) references ROLE,
    primary key (account_id, role_id)
);


INSERT INTO ADDRESS (street_name, city) values('Avenue des champs Elysées', 'Paris');
INSERT INTO ADDRESS (street_name, city) values('Park avenue', 'New-York');
INSERT INTO ADDRESS (street_name, city) values('Tochomae', 'Tokyo');
INSERT INTO ADDRESS (street_name, city) values('California Street', 'San Francisco');
INSERT INTO ADDRESS (street_name, city) values('742 Evergreen Terrasse', 'Springfield');

INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000001', 'admin', 'admin', 'admin@example.com', true, 1);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000002', 'user',  'user',  'user@example.com', true, 2);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000003', 'demo',  'demo',  'demo@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000004', 'user04',  'user04',  'user04@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000005', 'user05',  'user05',  'user05@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000006', 'user06',  'user06',  'user06@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000007', 'user07',  'user07',  'user07@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000008', 'user08',  'user08',  'user08@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000009', 'user09',  'user09',  'user09@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000010', 'user10',  'user10',  'user10@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000011', 'user11',  'user11',  'user11@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000012', 'user12',  'user12',  'user12@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000013', 'user13',  'user13',  'user13@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000014', 'user14',  'user14',  'user14@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000015', 'user15',  'user15',  'user15@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000016', 'user16',  'user16',  'user16@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000017', 'user17',  'user17',  'user17@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000018', 'user18',  'user18',  'user18@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000019', 'user19',  'user19',  'user19@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000020', 'user20',  'user20',  'user20@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000021', 'user21',  'user21',  'user21@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000022', 'user22',  'user22',  'user22@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000023', 'user23',  'user23',  'user23@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000024', 'user24',  'user24',  'user24@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000025', 'user25',  'user25',  'user25@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000026', 'user26',  'user26',  'user26@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000027', 'user27',  'user27',  'user27@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000028', 'user28',  'user28',  'user28@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000029', 'user29',  'user29',  'user29@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000030', 'user30',  'user30',  'user30@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000031', 'user31',  'user31',  'user31@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000032', 'user32',  'user32',  'user32@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000033', 'user33',  'user33',  'user33@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000034', 'user34',  'user34',  'user34@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000035', 'user35',  'user35',  'user35@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000036', 'user36',  'user36',  'user36@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000037', 'user37',  'user37',  'user37@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000038', 'user38',  'user38',  'user38@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000039', 'user39',  'user39',  'user39@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000040', 'user40',  'user40',  'user40@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000041', 'user41',  'user41',  'user41@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000042', 'user42',  'user42',  'user42@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000043', 'user43',  'user43',  'user43@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000044', 'user44',  'user44',  'user44@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000045', 'user45',  'user45',  'user45@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000046', 'user46',  'user46',  'user46@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000047', 'user47',  'user47',  'user47@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000048', 'user48',  'user48',  'user48@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000049', 'user49',  'user49',  'user49@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000050', 'user50',  'user50',  'user50@example.com', true, 3);
INSERT INTO ACCOUNT (id, login, password, email, is_enabled, address_id) VALUES ('0000000000000000000000000000051', 'disabled',  'disabled',  'disabled@example.com', false, 3);
INSERT INTO ACCOUNT (id, login, password, email, civility, address_id, birth_date) VALUES ('0000000000000000000000000000052', 'homer',  'homer',  'homer@example.com', 'MR', 4, PARSEDATETIME('01/01/1972','dd/mm/yyyy'));
INSERT INTO ACCOUNT (id, login, password, email, civility, address_id, birth_date) VALUES ('0000000000000000000000000000053', 'maggy',  'maggy',  'maggy@example.com', 'MS', 4, PARSEDATETIME('01/01/1982','dd/mm/yyyy'));

INSERT INTO ROLE (role_name) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE (role_name) VALUES ('ROLE_USER');

INSERT INTO ACCOUNT_ROLE (account_id, role_id) VALUES ('0000000000000000000000000000001', 1);
INSERT INTO ACCOUNT_ROLE (account_id, role_id) VALUES ('0000000000000000000000000000001', 2);
INSERT INTO ACCOUNT_ROLE (account_id, role_id) VALUES ('0000000000000000000000000000002', 2);
INSERT INTO ACCOUNT_ROLE (account_id, role_id) VALUES ('0000000000000000000000000000003', 2);
